# These are supported funding model platforms

github: [stayrahul]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: stayrahul
custom: https://www.buymeacoffee.com/stayrahul
